name: Release Mobile Control Tool

on:
  push:
    branches: [ main ]
    paths:
      - '_assets.yaml'
      - 'main.py'
      - 'requirements.txt'
      - 'package_tool.sh'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python test_tool.py

  package:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make package script executable
      run: chmod +x package_tool.sh

    - name: Package tool
      run: ./package_tool.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mobile-control-tool
        path: mobile_control_tool.zip
        retention-days: 30

  release:
    needs: package
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: mobile-control-tool

    - name: Generate release notes
      id: release_notes
      run: |
        # 获取最近的提交信息作为release notes
        RELEASE_NOTES=$(git log --oneline -10 --pretty=format:"- %s")
        echo "notes<<EOF" >> $GITHUB_OUTPUT
        echo "## What's Changed" >> $GITHUB_OUTPUT
        echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "## Installation" >> $GITHUB_OUTPUT
        echo "Download \`mobile_control_tool.zip\` and import it to Dify Studio." >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Mobile Control Tool v${{ github.run_number }}
        body: ${{ steps.release_notes.outputs.notes }}
        files: mobile_control_tool.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
